# Generated by Django 4.2.1 on 2023-06-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surename', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(choices=[('1', 'Yengil automobil'), ('2', 'Yuk automobil'), ('3', 'sport automobil')], max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Mashina haqida qisqacha ma`lumot', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel', models.CharField(choices=[('1', 'Benzin'), ('2', 'Dizel'), ('3', 'Gas')], default='1', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apphome.driver')),
            ],
        ),
    ]
